name: GestureTarget
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py311hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=25.0=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - addict==2.4.0
      - albucore==0.0.23
      - albumentations==2.0.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrs==25.1.0
      - av==14.1.0
      - beautifulsoup4==4.13.3
      - black==21.4b2
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==4.0.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - diffusers==0.32.2
      - distro==1.9.0
      - duckduckgo-search==7.3.2
      - einops==0.8.1
      - filelock==3.17.0
      - flash-attn==2.7.4.post1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - googlemaps==4.10.0
      - grpcio==1.70.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - hydra-core==1.3.2
      - idna==3.10
      - iglovikov-helper-functions==0.0.53
      - imagecorruptions==1.1.2
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - iopath==0.1.9
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - jpeg4py==0.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.9.2
      - kiwisolver==1.4.8
      - kornia==0.7.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - lit==18.1.8
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markdownify==0.14.1
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - narwhals==1.33.0
      - networkx==3.4.2
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.64.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.15.0
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.1.0
      - platformdirs==4.3.6
      - portalocker==3.1.1
      - primp==0.12.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pycocotools==2.0.8
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pydot==3.0.4
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.8
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retinaface-pytorch==0.0.7
      - rich==13.9.4
      - rpds-py==0.24.0
      - safetensors==0.5.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - selenium==4.28.1
      - sentencepiece==0.2.0
      - simsimd==6.2.1
      - six==1.17.0
      - smmap==5.0.2
      - smolagents==1.8.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - streamlit==1.44.1
      - stringzilla==3.12.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - timm==1.0.14
      - tokenizers==0.21.0
      - toml==0.10.2
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.49.0
      - trio==0.28.0
      - trio-websocket==0.11.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - watchdog==6.0.0
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xformers==0.0.29.post3
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.21.0
